name: Pull Request

on:
  pull_request:

jobs:
  qa:
    uses: ./.github/workflows/qa.yml
    # run qa job if the pull request originates from a fork (otherwise the qa is already triggered by the push to a branch)
    if: github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
