name: QA

on:
  workflow_call:

jobs:
  check-qa:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        run: |
          pip install -U pip
          pip install -e .[lint,check,scripts,test]

      - name: Check black formatting
        run: inv lint-black

      - name: Check ruff
        run: inv lint-ruff

      - name: Check pyright
        run: inv check-pyright
